jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build DTC Service
        run: mvn -B clean install -DskipTests
        working-directory: cd dtc-service

      - name: Build Notification Service
        run: mvn -B clean install -DskipTests
        working-directory: cd notification-service

      - name: Build Vehicle Health Service
        run: mvn -B clean install -DskipTests
        working-directory: cd vehicle-health-service
