name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # List all your Maven-based services here
        service: ['dtc-service', 'notification-service', 'vehicle-health-service']
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'  # Auto-configures Maven caching

      - name: Build and Test ${{ matrix.service }}
        run: |
          cd ${{ matrix.service }}
          mvn -B verify --file pom.xml  # Explicit POM file reference

      # Optional: Add test reports
      - name: Upload Test Results
        if: always()  # Runs even if tests fail
        uses: actions/upload-artifact@v3
        with:
          name: test-results-${{ matrix.service }}
          path: ${{ matrix.service }}/target/surefire-reports